; 星集控被控端 · 安装程序（NSIS 3）
;
; 三个设计要点：
;   1. **装机参数因机器而异**（云端地址 / 设备令牌 / 设备 uid）→ 放在安装向导里输入，
;      装完写成 agent.env。不让装机的人去手工编辑文件（他会漏、会写错）。
;   2. **自启沿用 install-autostart.ps1**（登录触发器计划任务，不是 Windows Service）：
;      真 Service 跑在 Session0，抓不到交互桌面 —— 锁屏/输入注入/截屏全会打在空白会话上。
;      NSIS 只负责「解包 + 写配置 + 调它」，**建任务的逻辑只有一份**，避免两处分叉。
;   3. **安装目录固定、不让改** —— 卸载时要 `RMDir /r`，如果放任用户把目录选成 C:\ 或已有目录，
;      那就是一次误删事故。固定成 C:\Program Files\Stelarith 之后，这个递归删除才是安全的。
;
; 构建：makensis installer.nsi      （工作目录＝本文件所在目录）

Unicode true
!include "MUI2.nsh"
!include "nsDialogs.nsh"
!include "LogicLib.nsh"
!include "FileFunc.nsh"     ; ${GetParameters} / ${GetOptions}：无人值守装机传参用（2026-10-06 加）

!define APPNAME "星集控被控端"
!define APPID   "StelarithAgentQt"
!define VER     "0.6.0"

Name "${APPNAME}"
OutFile "dist\stelarith-agent-setup.exe"
InstallDir "$PROGRAMFILES64\Stelarith"
InstallDirRegKey HKLM "Software\${APPID}" "InstallDir"
RequestExecutionLevel admin
SetCompressor /SOLID lzma

; ── 装机输入（默认值给好，装 TEST1 时基本只要改 uid）──
Var DlgUrl
Var DlgToken
Var DlgUid
Var Url
Var Token
Var Uid

!define MUI_ABORTWARNING
!insertmacro MUI_PAGE_WELCOME
Page custom ConfigPageCreate ConfigPageLeave
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES
!insertmacro MUI_LANGUAGE "SimpChinese"

Function .onInit
	StrCpy $Url   "ws://127.0.0.1:8788/ws/agent"
	StrCpy $Token ""
	StrCpy $Uid   "TEST1"

	; ── 无人值守装机：从命令行读配置（2026-10-06 加）────────────────────────
	; 为什么必须有：云端的 assets/provision/install-agent.ps1（浏览器点一下 → 教室机双击 bat
	; 那条链）就是 `Start-Process $pkg -ArgumentList "/S"` 静默装的。静默模式下向导页不显示，
	; 这三项如果只能手填，无人值守这条路就断了 —— 而它恰恰是"零成本维护"的入口。
	; 用法：stelarith-agent-setup.exe /S /UID=class_xlzx_2028_08 /URL=wss://.../ws/agent /TOKEN=xxx
	; 不给参数就退回上面的默认值（行为与改动前一致）。
	${GetParameters} $R0
	${GetOptions} $R0 "/UID="   $R1
	${If} $R1 != ""
		StrCpy $Uid $R1
	${EndIf}
	${GetOptions} $R0 "/URL="   $R1
	${If} $R1 != ""
		StrCpy $Url $R1
	${EndIf}
	${GetOptions} $R0 "/TOKEN=" $R1
	${If} $R1 != ""
		StrCpy $Token $R1
	${EndIf}
FunctionEnd

Function ConfigPageCreate
	; ⚠️ 静默安装(/S)必须**跳过本页**：无桌面时 nsDialogs::Create 返回 error，
	;    而下面的 ${If} $0 == error { Abort } 会把**整个安装**中止掉。
	;    实测：不改这里，`setup.exe /S` 退出码 2、什么都没装 —— 云端那条无人值守装机链
	;    (install-agent.ps1 第 95 行 /S) 就是死在这一步，而且现场只看到"装了但没反应"。
	${If} ${Silent}
		Abort
	${EndIf}

	!insertmacro MUI_HEADER_TEXT "装机参数" "这三项因机器而异；装完会写成 agent.env"
	nsDialogs::Create 1018
	Pop $0
	${If} $0 == error
		Abort
	${EndIf}

	${NSD_CreateLabel} 0 0 100% 22u "云端地址 / 设备令牌 / 设备 uid 会写进 agent.env。$\r$\n不确定就先按默认装，之后改 $\"$INSTDIR\agent.env$\" 再重启被控端。"
	Pop $0

	${NSD_CreateLabel} 0 30u 100% 11u "云端地址（ws://主机:8788/ws/agent）"
	Pop $0
	${NSD_CreateText} 0 42u 100% 13u "$Url"
	Pop $DlgUrl

	${NSD_CreateLabel} 0 62u 100% 11u "设备令牌（要与云端 CLOUD_WS_TOKEN 一致；留空则云端会拒绝）"
	Pop $0
	${NSD_CreateText} 0 74u 100% 13u "$Token"
	Pop $DlgToken

	${NSD_CreateLabel} 0 94u 100% 11u "设备 uid（这台机器的代号，例如 TEST1）"
	Pop $0
	${NSD_CreateText} 0 106u 100% 13u "$Uid"
	Pop $DlgUid

	nsDialogs::Show
FunctionEnd

Function ConfigPageLeave
	${NSD_GetText} $DlgUrl   $Url
	${NSD_GetText} $DlgToken $Token
	${NSD_GetText} $DlgUid   $Uid
FunctionEnd

Section "install"
	SetOutPath "$INSTDIR"

	; 先停掉正在跑的旧实例：否则 exe 被占用，覆盖会失败。
	; 用 PowerShell 的 Stop-Process，**不用 taskkill** —— cmd 系工具语义模糊、返回难判断，
	; 在这台机器上还容易被执行策略/路径转换绊住；cmdlet 的行为是可预期的。
	nsExec::ExecToLog 'powershell -NoProfile -Command "Get-Process -Name stelarith-agent-qt -ErrorAction SilentlyContinue | Stop-Process -Force"'
	Sleep 800

	; 装机包全部内容（exe + Qt 运行时 + styles + 脚本 + 说明）
	File /r "deploy\*.*"

	; 写 agent.env —— 让 exe 直接可用，装机的人不用手改文件。
	; 兜底：静默安装（/S）不走向导页，这三个变量可能从未被赋值 —— 别把空值写进配置文件
	${If} $Url == ""
		StrCpy $Url "ws://127.0.0.1:8788/ws/agent"
	${EndIf}
	${If} $Uid == ""
		StrCpy $Uid "TEST1"
	${EndIf}

	; ⚠️ 注释行**必须纯 ASCII**：第一版这里写了中文，结果在 GBK 终端里显示成乱码
	;    （写文件的编码和读的人不一致）。配置文件里的注释不值得为它引一个编码问题。
	FileOpen $0 "$INSTDIR\agent.env" w
	FileWrite $0 "rem Generated by installer. Edit values, then restart the agent.$\r$\n"
	FileWrite $0 "set STE_QT_WS_URL=$Url$\r$\n"
	FileWrite $0 "set STE_QT_WS_TOKEN=$Token$\r$\n"
	FileWrite $0 "set STE_QT_UID=$Uid$\r$\n"
	FileWrite $0 "set STE_QT_SHOT_DIR=$INSTDIR\shots$\r$\n"
	FileClose $0

	; 建登录触发器计划任务 —— 逻辑在 ps1 里（-SkipCopy：文件已由本安装器放好）
	nsExec::ExecToLog 'powershell -NoProfile -ExecutionPolicy Bypass -File "$INSTDIR\install-autostart.ps1" -SkipCopy -Dest "$INSTDIR"'

	; 卸载信息（控制面板里能看到）
	WriteRegStr HKLM "Software\${APPID}" "InstallDir" "$INSTDIR"
	WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APPID}" "DisplayName"     "${APPNAME}（星集控）"
	WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APPID}" "DisplayIcon"     "$INSTDIR\stelarith-agent-qt.exe"
	WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APPID}" "DisplayVersion"  "${VER}"
	WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APPID}" "Publisher"       "Stelarith"
	WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APPID}" "UninstallString" "$INSTDIR\uninstall.exe"
	WriteUninstaller "$INSTDIR\uninstall.exe"
SectionEnd

Section "un.install"
	; 先删任务（不然它可能把进程再拉起来），再杀进程
	nsExec::ExecToLog 'powershell -NoProfile -ExecutionPolicy Bypass -File "$INSTDIR\install-autostart.ps1" -Uninstall'
	; 同样用 Stop-Process，不用 taskkill
	nsExec::ExecToLog 'powershell -NoProfile -Command "Get-Process -Name stelarith-agent-qt -ErrorAction SilentlyContinue | Stop-Process -Force"'
	Sleep 800

	Delete "$INSTDIR\uninstall.exe"

	; 删安装目录。为什么这里直接 RMDir /r 是安全的：
	;   本安装器**没有目录选择页**，$INSTDIR 恒为 "$PROGRAMFILES64\Stelarith" ——
	;   不可能指向盘根或别的程序的目录。当初去掉目录选择页，就是为了让这一次递归删除站得住脚。
	RMDir /r "$INSTDIR"

	DeleteRegKey HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APPID}"
	DeleteRegKey HKLM "Software\${APPID}"

	; 注意：**不删数据目录** %LOCALAPPDATA%\xingjikong（里面有历史日志与截图，
	; 留证比"清干净"重要；要清由人自己决定）
SectionEnd
