@echo off
rem Stelarith controlled terminal - MSI post-install script (called once by installer)
rem   1) write default agent.env (pure ASCII comments, no GBK mojibake)
rem   2) reuse install-autostart.ps1 to create the logon autostart task (single source of truth)
rem
rem WHY .cmd instead of inline PowerShell:
rem   WiX CustomAction ExeCommand treats [ as a property reference and \v as an escape
rem   (both cause WIX0104). Put all logic in a script file; the installer just calls it.
rem
rem IMPORTANT ENCODING RULE: this file MUST stay pure ASCII and use CRLF line endings.
rem   cmd.exe parses .cmd files with the ANSI codepage (GBK 936 on this machine).
rem   UTF-8 Chinese comment bytes break parsing -> script dies on the first line
rem   (observed: post-install log in ProgramData was never even created).
rem
rem IMPORTANT ARG RULE (2026-10-03): the CustomAction passes NO arguments at all.
rem   Earlier we passed the install dir as a trailing arg, but ExeCommand renders it as
rem   "...\Stelarith\" -> the trailing backslash-quote is an ESCAPED QUOTE in the Windows
rem   C runtime command line parser -> unbalanced quotes -> cmd.exe /c mangles the whole
rem   line -> script never runs (log was never written, agent.env never created).
rem   Fix: derive Dest from %~dp0 (this script's own directory) and strip trailing backslash.
rem
rem runs in SYSTEM context (MSI deferred + Impersonate=no). Every step logs to ProgramData
rem so any failure is attributable (rollback removes the install dir but not ProgramData).

setlocal
rem %~dp0 = directory of this script, WITH trailing backslash (e.g. C:\Program Files\Stelarith\)
set "Dest=%~dp0"
if "%Dest:~-1%"=="\" set "Dest=%Dest:~0,-1%"
if "%Dest%"=="" set "Dest=%ProgramFiles%\Stelarith"

set "LOG=%ProgramData%\stelarith-msi-postinstall.log"
> "%LOG%" echo === post-install start %DATE% %TIME% ===
>> "%LOG%" echo Dest=%Dest%

rem 1) write agent.env (ASCII)
> "%Dest%\agent.env" (
  echo rem Generated by installer. Edit values, then restart the agent.
  echo set "STE_QT_WS_URL=ws://127.0.0.1:8788/ws/agent"
  echo set "STE_QT_WS_TOKEN="
  echo set "STE_QT_UID=TEST1"
  echo set "STE_QT_SHOT_DIR=%Dest%\shots"
)
if errorlevel 1 (
  >> "%LOG%" echo [FAIL] agent.env write, errorlevel=%ERRORLEVEL%
  exit /b 1
)
>> "%LOG%" echo [ok] agent.env written

rem 2) create logon autostart task (files already placed by installer, skip copy)
powershell -NoProfile -ExecutionPolicy Bypass -File "%Dest%\install-autostart.ps1" -SkipCopy -Dest "%Dest%" >> "%LOG%" 2>&1
set "PSRC=%ERRORLEVEL%"
>> "%LOG%" echo [exit] install-autostart.ps1 errorlevel=%PSRC%
if not "%PSRC%"=="0" exit /b %PSRC%

exit /b 0