param(
    # 这台教室机的唯一代号，按命名规范：class_<校简称>_<届>_<班号>
    # 例：  -Uid class_xlzx_2028_08
    [Parameter(Mandatory = $true)][string]$Uid,

    # 云端地址（公网上线后用 wss://；本机联调可用 ws://127.0.0.1:8788/ws/agent）
    [Parameter(Mandatory = $true)][string]$CloudUrl,

    # 设备令牌：必须与云端 .env 的 CLOUD_WS_TOKEN 一致
    [Parameter(Mandatory = $true)][string]$Token,

    # 安装包路径（默认取本脚本同目录的 stelarith-agent-setup.exe）
    [string]$Installer,

    # 安装目录（固定，别改 —— 卸载时按此递归删除）
    [string]$InstallDir = "C:\Program Files\Stelarith",

    # 只打印将要做什么，不实际执行
    [switch]$WhatIfOnly
)

# ASCII only. 教室机一键装机：静默装 -> 写 agent.env -> 重启自启任务 -> 自检。
# 幂等：重复跑会先卸旧实例、覆写配置，不会装出两份。
# ⚠️ 需要管理员权限运行。

$ErrorActionPreference = "Stop"
function Info($m) { Write-Host "[*] $m" -ForegroundColor Cyan }
function Ok($m)   { Write-Host "[OK] $m" -ForegroundColor Green }
function Warn($m) { Write-Host "[!] $m" -ForegroundColor Yellow }
function Die($m)  { Write-Host "[X] $m" -ForegroundColor Red; exit 1 }

if (-not ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Die "需要管理员权限。请以管理员身份重开 PowerShell 再运行。"
}

if (-not $Installer) {
    # 依次找：本脚本同目录 -> 工作台的 control-qt\dist
    $cand = @(
        (Join-Path $PSScriptRoot "stelarith-agent-setup.exe"),
        (Join-Path $PSScriptRoot "..\Stelarith-control-qt\dist\stelarith-agent-setup.exe")
    )
    foreach ($c in $cand) { if (Test-Path $c) { $Installer = (Resolve-Path $c).Path; break } }
}
if (-not $Installer -or -not (Test-Path $Installer)) { Die "找不到安装包。请把 stelarith-agent-setup.exe 放到本脚本同目录，或用 -Installer <路径> 指定。" }

# 命名规范自检（软校验，只告警不阻断）
if ($Uid -notmatch '^(class|admin)_[a-z0-9]+_\d{4}_\d{1,3}$') {
    Warn "uid '$Uid' 不符合命名规范 class_<校简称>_<届>_<班号>（例 class_xlzx_2028_08）。"
}
if ($Uid -cne $Uid.ToLower()) { Warn "uid 含大写字母，云端按原样存，建议全小写。" }

Info "目标 uid   = $Uid"
Info "云端地址   = $CloudUrl"
Info ("令牌        = <{0} 字符，不打印>" -f $Token.Length)
Info "安装包     = $Installer"
Info "安装目录   = $InstallDir"
Write-Host ""

if ($WhatIfOnly) { Warn "-WhatIfOnly：未执行任何改动。"; exit 0 }

# ---- 1) 停掉正在跑的旧实例（含旧的 ClassIsland 被控端残留）----
Info "停止旧的被控端进程（若有）..."
Get-Process -Name 'stelarith-agent-qt','stelarith-guard','stelarith-agent' -ErrorAction SilentlyContinue |
    ForEach-Object { try { Stop-Process -Id $_.Id -Force -ErrorAction SilentlyContinue; Ok "已停 PID $($_.Id) ($($_.ProcessName))" } catch {} }
Start-Sleep -Milliseconds 800

# ---- 2) 静默安装（NSIS /S：不走向导，用默认值；下面再用参数覆写配置）----
Info "静默安装（NSIS /S，约 10-30 秒）..."
$p = Start-Process -FilePath $Installer -ArgumentList "/S" -Wait -PassThru
if ($p.ExitCode -ne 0) { Warn "安装器返回 $($p.ExitCode)（非 0 不一定是失败，继续校验产物）" } else { Ok "安装器完成" }

$exe = Join-Path $InstallDir "stelarith-agent-qt.exe"
if (-not (Test-Path $exe)) { Die "安装后仍找不到 $exe —— 安装失败，请检查安装包与权限。" }
Ok "exe 就位：$exe ($((Get-Item $exe).Length) 字节)"

# ---- 3) 覆写 agent.env（把默认值换成这台机器的真配置）----
Info "写 agent.env ..."
$envFile = Join-Path $InstallDir "agent.env"
@(
    "rem Generated by install-classroom-agent.ps1 -- edit values, then restart the agent.",
    "set STE_QT_WS_URL=$CloudUrl",
    "set STE_QT_WS_TOKEN=$Token",
    "set STE_QT_UID=$Uid",
    "set STE_QT_SHOT_DIR=$InstallDir\shots"
) | Set-Content -Path $envFile -Encoding ASCII
Ok "已写 $envFile"

# ---- 4) 重启登录触发器任务，让新进程按新配置起来 ----
$task = 'StelarithAgentQt'
if (Get-ScheduledTask -TaskName $task -ErrorAction SilentlyContinue) {
    Info "重启计划任务 $task ..."
    Stop-ScheduledTask -TaskName $task -ErrorAction SilentlyContinue
    Start-ScheduledTask  -TaskName $task -ErrorAction SilentlyContinue
    Start-Sleep -Seconds 3
} else {
    Warn "计划任务 $task 不存在 —— 安装器应已创建；若没有，请手工跑 $InstallDir\install-autostart.ps1 -SkipCopy"
}

# ---- 5) 自检 ----
Info "自检 ..."
$proc = Get-Process -Name 'stelarith-agent-qt' -ErrorAction SilentlyContinue
if ($proc) { Ok "被控端进程在跑：PID $($proc.Id -join ','), 内存 $([math]::Round(($proc | Select-Object -First 1).WorkingSet64/1MB,1)) MB" }
else { Warn "没看到被控端进程 —— 可能被杀软拦了，或被单例锁挡住（先确认没有别的实例）。" }

$logFile = Join-Path $env:LOCALAPPDATA "xingjikong\agent-qt.log"
if (Test-Path $logFile) {
    Info "日志尾部（$logFile）："
    Get-Content $logFile -Tail 6 | ForEach-Object { "      $_" }
}

Write-Host ""
Ok "装机完成。到云端核对："
Write-Host "    curl -H `"Authorization: Bearer <CLOUD_VIEWER_TOKEN>`" <云端HTTP地址>/api/devices"
Write-Host "    应能看到 uid=$Uid、online=true、version=0.5.0"
Write-Host ""
Write-Host "台账请记一行： uid=$Uid  班级=<班>  位置=<教室>  装机日期=$(Get-Date -Format 'yyyy-MM-dd')"
